services:
  postgres:
    image: postgres:16.1
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DOCKER_DATABASE_NAME}
      POSTGRES_USER: ${DOCKER_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DOCKER_DATABASE_USERNAME}:${DOCKER_DATABASE_PASSWORD}@postgres:5432/${DOCKER_DATABASE_NAME}

    volumes:
      - uploads_data:/app/uploads

volumes:
  postgres_data:
  uploads_data:
